from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

from .schema import Script
from .utils import slugify


def _run_ffmpeg(args: list[str]) -> None:
    r = subprocess.run(
        ["ffmpeg", "-y", *args],
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        err = (r.stderr or r.stdout or "").strip()
        raise RuntimeError(f"ffmpeg failed ({r.returncode}): {err[-2000:]}")


def _find_segment_still(images_dir: Path, idx: int, seg_char: str, seg_emotion: str) -> Path | None:
    """Comfy SaveImage may be .png / .webp / .jpg depending on workflow or settings."""
    stem = slugify(f"{idx:03d}_{seg_char}_{seg_emotion}")
    for ext in (".png", ".webp", ".jpg", ".jpeg"):
        p = images_dir / f"{stem}{ext}"
        if p.is_file():
            return p
    return None


def try_build_master_mp4(
    *,
    script: Script,
    segment_wavs: list[Path],
    images_dir: Path,
    out_mp4: Path,
    width: int = 1280,
    height: int = 720,
) -> Path:
    """
    One slide per segment: still image (or black if missing) for the length of that segment's WAV.
    Concatenates to a single MP4 with audio.

    Requires `ffmpeg` on PATH. This is not generated by LLM/Comfy prompts alone — you need
    segment audio (and optionally images); this step muxes them.
    """
    if len(segment_wavs) != len(script.segments):
        raise ValueError("segment_wavs length must match script.segments")

    out_mp4.parent.mkdir(parents=True, exist_ok=True)
    vf = (
        f"scale={width}:{height}:force_original_aspect_ratio=decrease,"
        f"pad={width}:{height}:(ow-iw)/2:(oh-ih)/2,format=yuv420p"
    )

    clips: list[Path] = []
    with tempfile.TemporaryDirectory(prefix="devaemon_mp4_") as tmp:
        tmp_root = Path(tmp)
        last_still: Path | None = None
        for i, seg in enumerate(script.segments, start=1):
            wav = segment_wavs[i - 1]
            clip_path = tmp_root / f"clip_{i:03d}.mp4"
            img = _find_segment_still(images_dir, i, seg.char, seg.emotion)
            if img is not None:
                last_still = img
            elif last_still is not None:
                img = last_still

            if img is not None and img.is_file():
                _run_ffmpeg(
                    [
                        "-loop",
                        "1",
                        "-i",
                        str(img.resolve()),
                        "-i",
                        str(wav.resolve()),
                        "-vf",
                        vf,
                        "-shortest",
                        "-c:v",
                        "libx264",
                        "-tune",
                        "stillimage",
                        "-c:a",
                        "aac",
                        "-ar",
                        "48000",
                        "-ac",
                        "1",
                        str(clip_path.resolve()),
                    ]
                )
            else:
                _run_ffmpeg(
                    [
                        "-f",
                        "lavfi",
                        "-i",
                        f"color=c=black:s={width}x{height}:r=30",
                        "-i",
                        str(wav.resolve()),
                        "-vf",
                        "format=yuv420p",
                        "-shortest",
                        "-c:v",
                        "libx264",
                        "-c:a",
                        "aac",
                        "-ar",
                        "48000",
                        "-ac",
                        "1",
                        str(clip_path.resolve()),
                    ]
                )
            clips.append(clip_path)

        list_file = tmp_root / "concat.txt"
        lines: list[str] = []
        for c in clips:
            lines.append(f"file '{c.resolve().as_posix()}'")
        list_file.write_text("\n".join(lines) + "\n", encoding="utf-8")

        _run_ffmpeg(
            [
                "-f",
                "concat",
                "-safe",
                "0",
                "-i",
                str(list_file.resolve()),
                "-c",
                "copy",
                str(out_mp4.resolve()),
            ]
        )

    return out_mp4
